// <auto-generated />
using System;
using DeliveryApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryApi.Migrations
{
    [DbContext(typeof(VertaDbContext))]
    [Migration("20260730112345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeliveryApi.Models.Address", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Apartment")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("apartment");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("house");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("DeliveryApi.Models.Cargo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("cargo", (string)null);
                });

            modelBuilder.Entity("DeliveryApi.Models.Order", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateOnly>("DatePickup")
                        .HasColumnType("date")
                        .HasColumnName("datePickup");

                    b.Property<ulong>("IdCargo")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("idCargo");

                    b.Property<ulong>("IdRecipientAddress")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("idRecipientAddress");

                    b.Property<ulong>("IdSenderAddress")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("idSenderAddress");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCargo" }, "idCargo");

                    b.HasIndex(new[] { "IdRecipientAddress" }, "idRecipientAddress");

                    b.HasIndex(new[] { "IdSenderAddress" }, "idSenderAddress");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("DeliveryApi.Models.Order", b =>
                {
                    b.HasOne("DeliveryApi.Models.Cargo", "IdCargoNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdCargo")
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_3");

                    b.HasOne("DeliveryApi.Models.Address", "IdRecipientAddressNavigation")
                        .WithMany("OrderIdRecipientAddressNavigations")
                        .HasForeignKey("IdRecipientAddress")
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_2");

                    b.HasOne("DeliveryApi.Models.Address", "IdSenderAddressNavigation")
                        .WithMany("OrderIdSenderAddressNavigations")
                        .HasForeignKey("IdSenderAddress")
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_1");

                    b.Navigation("IdCargoNavigation");

                    b.Navigation("IdRecipientAddressNavigation");

                    b.Navigation("IdSenderAddressNavigation");
                });

            modelBuilder.Entity("DeliveryApi.Models.Address", b =>
                {
                    b.Navigation("OrderIdRecipientAddressNavigations");

                    b.Navigation("OrderIdSenderAddressNavigations");
                });

            modelBuilder.Entity("DeliveryApi.Models.Cargo", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
